### ISSUE TITLE
issue when loading 0.14

### ISSUE THREAD

**Issue by Bats92** [Oarcinae/FactorioUtils#1]
Just to confirm, is there a 0.14 version of the utils?
When attempting to load the scenario errors are thrown up see below;

![image](https://cloud.githubusercontent.com/assets/28389932/25701640/184b45be-30c5-11e7-9639-2e81bf5c75fc.png)

**Comment by Oarcinae** [comment]
I'll tag the last V0.14 (to be used with the V0.14 scenario code).
